### ISSUE TITLE
Bug: when a command center is destroyed server gets a bug and crash

### ISSUE THREAD

**Issue by sagittarius89** [sagittarius89/Tower-Defense#24]
C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\server\gameobjects\soldier.js:122
        const enemyPos = new Vector2d(enemy.x, enemy.y);
                                            ^

TypeError: Cannot read property 'x' of null
    at Soldier.checkLineOfFire (C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\server\gameobjects\soldier.js:122:45)
    at Soldier.logic (C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\server\gameobjects\soldier.js:102:19)
    at C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\server\serverengine.js:104:21
    at GameObjectList.foreach (C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\game\static\src\gameobjectlist.js:64:17)
    at GameEngine.update (C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\server\serverengine.js:103:21)
    at GameEngine.<anonymous> (C:\Users\lenovo\Documents\Programowanie\Tower Defense 2\Tower-Defense\server\serverengine.js:110:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by sagittarius89** [comment]
3e9e9af681ad7ec5cbdde980d17a46d906b56f79
